<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mediaplans</name>
   <tag></tag>
   <elementGuidId>5b7e1395-7c79-49bd-9257-3561d2722f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>&quot;//a[contains(@href,'#/mediaplans/list')]&quot;</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;top-nav&quot;]/div[2]/ul[1]/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;top-nav&quot;]/div[2]/ul[1]/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
